import { writeFile } from "node:fs/promises";

const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sudoku phone check</title><style>body{font:17px system-ui;max-width:650px;margin:20px auto;padding:16px}button{font:inherit;margin:10px;padding:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere}label{display:block}textarea{width:95%}</style><h1>Phone generation check</h1><p>This checks the provisional effort policy on your actual device. It does not change your saved games or production difficulty settings. It runs five requests per browser-generated level.</p><button id="run">Run check</button><button id="stop">Stop</button><p id="status">Ready</p><pre id="results"></pre><label>Device and experience notes<textarea id="notes" rows="4" placeholder="Phone model, browser, visible pauses, repeated puzzles during normal play"></textarea></label><button id="export">Export results</button><p>Also play a few samples in <a href="playtest.html">the playtest set</a>. Device timings alone cannot establish perceived difficulty.</p><script type="module">
const el=id=>document.getElementById(id);let worker=null,stop=false,abort=null,report={policyVersion:2,userAgent:navigator.userAgent,cores:navigator.hardwareConcurrency,screen:{width:screen.width,height:screen.height},simulation:false,samples:[],notes:''};
el('stop').onclick=()=>{stop=true;abort?.();if(worker)worker.terminate();worker=null;el('run').disabled=false;el('status').textContent='Stopped; partial results can be exported'};
el('run').onclick=async()=>{stop=false;el('run').disabled=true;report.samples=[];try{const policy=await(await fetch('proposed-policy.json')).json();report.policy=policy;worker=new Worker('/src/calibrationWorker.ts',{type:'module'});for(const difficulty of ['easy','medium','hard','master'])for(let n=0;n<5&&!stop;n++){el('status').textContent=difficulty+' '+(n+1)+'/5';const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Worker did not respond within 30 seconds')),30000);abort=()=>{clearTimeout(timer);reject(Error('Stopped'))};worker.onmessage=e=>{clearTimeout(timer);abort=null;resolve(e.data)};worker.onerror=e=>{clearTimeout(timer);reject(Error(e.message))};worker.postMessage({type:'generate',difficulty,policy,seed:500000+n*1000})});report.samples.push({difficulty,metrics:result.metrics,assessment:result.game?.assessment});el('results').textContent=report.samples.map(s=>s.difficulty+': '+Math.round(s.metrics.durationMs)+' ms, '+(s.metrics.accepted?'accepted':'no qualifying board')).join('\\n')}if(!stop){const start=performance.now();const {curatedExpertGames}=await import('/src/generated/curatedExpert.v1.ts');report.expertCatalog={count:curatedExpertGames.length,loadMs:performance.now()-start};el('status').textContent='Complete. Add notes and export results.'}}catch(e){report.error=String(e);el('status').textContent=String(e)}finally{worker?.terminate();worker=null;el('run').disabled=false}};
el('export').onclick=()=>{report.notes=el('notes').value;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download='sudoku-phone-check.json';a.click();URL.revokeObjectURL(a.href)};
</script></html>`;
await writeFile("scripts/output/calibration/phone.html", html);
